name: Foforecast Github actions
on:
  pull_request:
    branches:
      - main
jobs:
  Windguru-Crawler:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
          uses: actions/checkout@v2
      - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
      - name: Install dependencies
          working-directory: ./crawlers
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements_dev.txt
